PROJECT_NAME ?= sqlparser
LIB_NAME ?= sqlparser
SONAME_MAJOR ?= 0
VENDOR_PG_QUERY_TAG ?= 17-6.2.2
CROSS_COMPILE ?=

SQLPARSER_SITE_CONFIG ?= ./config/site.mk
include $(SQLPARSER_SITE_CONFIG)

ifneq ($(strip $(CROSS_COMPILE)),)
CC := $(CROSS_COMPILE)gcc
AR := $(CROSS_COMPILE)ar
RANLIB := $(CROSS_COMPILE)ranlib
NM := $(CROSS_COMPILE)nm
READELF := $(CROSS_COMPILE)readelf
else
ifeq ($(origin CC), default)
CC := gcc
endif
ifeq ($(origin AR), default)
AR := ar
endif
RANLIB ?= ranlib
NM ?= nm
READELF ?= readelf
endif

PTHREAD_CFLAGS ?= -pthread
PTHREAD_LDLIBS ?= -pthread

BUILD_PATH ?= ./build
OBJ_PATH ?= $(BUILD_PATH)/obj
BIN_PATH ?= ./bin
LIB_PATH ?= ./lib
PKGCONFIG_BUILD_DIR ?= $(BUILD_PATH)/pkgconfig

DEBUG ?= 0
SHOW_WARNING ?= 1

EXTRA_CPPFLAGS ?=
EXTRA_CFLAGS ?=
EXTRA_LDFLAGS ?=
EXTRA_LDLIBS ?=
