PROJECT_NAME ?= sqlparser
LIB_NAME ?= sqlparser
SONAME_MAJOR ?= 0
VENDOR_PG_QUERY_TAG ?= 17-6.2.2

ifeq ($(origin CC), default)
CC := gcc
endif

AR ?= ar
RANLIB ?= ranlib
PKG_CONFIG ?= pkg-config
PTHREAD_CFLAGS ?= -pthread
PTHREAD_LDLIBS ?= -pthread

SQLPARSER_SITE_CONFIG ?= ./config/site.mk
include $(SQLPARSER_SITE_CONFIG)

BUILD_PATH ?= ./build
OBJ_PATH ?= $(BUILD_PATH)/obj
BIN_PATH ?= ./bin
LIB_PATH ?= ./lib
PKGCONFIG_BUILD_DIR ?= $(BUILD_PATH)/pkgconfig

DEBUG ?= 1
SHOW_WARNING ?= 1

EXTRA_CPPFLAGS ?=
EXTRA_CFLAGS ?=
EXTRA_LDFLAGS ?=
EXTRA_LDLIBS ?=
