/* Shared source corpus; expected behavior comes from the frozen validator and
 * from the same public caller linked to the immutable accepted archive. */
static const char *const returningguard_cases[] = {
    "", " ", "RETURN", "returning", "RETURNING", "rEtUrNiNg", "rrreturning", "returningreturning",
    "SELECT 1 FROM dual", "SELECT )", "SELECT 'unterminated", "SELECT \"unterminated", "/* unterminated", "-- tail",
    "INSERT ALL INTO t(a,b) VALUES ('雪', CURRENT_TIMESTAMP) SELECT 1 FROM dual",
    "INSERT ALL INTO t(a) VALUES ('old') INTO t(a) VALUES ('keep') SELECT 1 FROM dual",
    "INSERT INTO t(a) VALUES (1) RETURNING a INTO :out",
    "UPDATE t SET a=1 RETURNING a,b INTO :out,:other",
    "DELETE FROM t RETURNING a INTO :1",
    "UPDATE t SET a=1 RETURNING a", "UPDATE t SET a=1 RETURNING a,b INTO :out",
    "UPDATE t SET a=1 RETURNING a INTO target", "UPDATE t SET a=1 RETURNING a BULK COLLECT INTO :out",
    "UPDATE t SET a=1 RETURNING ,a INTO :out", "UPDATE t SET a=1 RETURNING a, INTO :out",
    "UPDATE t SET a=1 RETURNING a INTO :out trailing", "UPDATE t SET a=1 RETURNING (a INTO :out",
    "UPDATE t SET a=1 RETURN a INTO :out", "UPDATE t SET a=1 RETURN a", "SELECT RETURNING FROM dual",
    "UPDATE t SET a=1 RETURNING a INTO :returning", "SELECT :returning FROM dual", "SELECT :return FROM dual",
    "SELECT returning_suffix, prefix_returning, $returning, #returning, returning9 FROM dual",
    "SELECT 雪returning, returning雪 FROM dual", "SELECT 'RETURNING' FROM dual", "SELECT \"RETURNING\" FROM dual",
    "SELECT 'can''t RETURNING' FROM dual", "SELECT E'escaped\\\' RETURNING' FROM dual",
    "SELECT N'RETURNING' FROM dual", "SELECT q'[RETURNING]' FROM dual", "SELECT nq'{RETURNING}' FROM dual",
    "SELECT q'(RETURNING)' FROM dual", "SELECT Q'<RETURNING>' FROM dual", "SELECT q'!RETURNING!' FROM dual",
    "SELECT q'[unterminated RETURNING", "SELECT nq'[unterminated RETURNING", "SELECT q' RETURNING '",
    "SELECT $$RETURNING$$ FROM dual", "SELECT $tag$RETURNING$tag$ FROM dual", "SELECT $tag$unterminated RETURNING",
    "SELECT U&'\\0052ETURNING' FROM dual", "SELECT U&\"\\0052ETURNING\" FROM dual",
    "SELECT U&'RETURNING' FROM dual", "SELECT U&\"RETURNING\" FROM dual",
    "SELECT 1 /* RETURNING */ FROM dual", "SELECT 1 -- RETURNING\nFROM dual",
    "SELECT 1 /* outer /* inner */ RETURNING */ FROM dual", "SELECT RET/* gap */URNING FROM dual",
    "SELECT RET-- gap\nURNING FROM dual", "SELECT 1; UPDATE t SET a=1 RETURNING a INTO :out; SELECT 2",
    "UPDATE t SET a=1 RETURNING a INTO :out; UPDATE t SET a=2 RETURNING a,b INTO :out",
    "SELECT ); UPDATE t SET a=1 RETURNING a INTO :out", "SELECT (UPDATE t SET a=1 RETURNING a INTO :out)",
    "ALTER SESSION SET CURRENT_SCHEMA = app; SELECT 1 FROM dual",
    "ALTER SESSION SET CURRENT_SCHEMA = app; UPDATE t SET a=1 RETURNING a,b INTO :out",
    "EXECUTE IMMEDIATE 'UPDATE t SET a=1 RETURNING a INTO :out'",
    "BEGIN NULL; END;", "SELECT CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM dual",
    "SELECT \001\037\177\200\377 FROM dual", "SELECT `RETURNING`, [RETURNING] FROM dual"
};
